version: "2.0"
services:
  elasticsearch:
    image: elasticsearch
  kibana:
    image: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  logstash:
    image: logstash
    volumes:
      - ./logs:/logs
      - ./logstash:/config
    command: logstash -f /config/logstash.conf
