version: "2.0"
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
  kibana:
    image: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  logstash:
    image: logstash
    volumes:
      - ./logs:/logs
      - ./logstash.conf:/logstash.conf
    command: logstash -f /logstash.conf
